### ISSUE TITLE
Connect Example API for State Machine

### ISSUE THREAD

**Issue by johntimothybailey** [DelveFore/ignite-hydrogen#12]
# Acceptance Criteria
As a user I should see the example users from the HTTP API on a screen. _Keep in mind currently the API we're using for users randomly generates users_

The users should be listed on the second screen after pressing "Continue"

**Comment by JonnoKiwi** [comment]
@johntimothybailey Is the end result for this issue is that there is a screen displaying users? If that's the case then there needs to be:
- A screen displaying a table for users
- A list of fake users
- An API that pulls that list of fake users for the user table

Correct me if I'm wrong

**Comment by johntimothybailey** [comment]
@JonnoKiwi naa Fake API is out of scope
